import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1775979617700 implements MigrationInterface {
    name = 'Migration1775979617700'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "IDX_4c9fb58de893725258746385e1"`);
        await queryRunner.query(`DROP INDEX "IDX_75895eeb1903f8a17816dafe0a"`);
        await queryRunner.query(`DROP INDEX "IDX_048a28949bb332d397edb9b7ab"`);
        await queryRunner.query(`CREATE TABLE "temporary_products" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(200) NOT NULL, "description" text NOT NULL, "price" decimal(10,2) NOT NULL, "stock" integer NOT NULL DEFAULT (0), "imagePath" varchar(255), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "subCategoryId" integer NOT NULL, CONSTRAINT "FK_ad42985fb27aa9016b16ee740ec" FOREIGN KEY ("subCategoryId") REFERENCES "sub_categories" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_products"("id", "name", "description", "price", "stock", "imagePath", "createdAt", "subCategoryId") SELECT "id", "name", "description", "price", "stock", "imagePath", "createdAt", "subCategoryId" FROM "products"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`ALTER TABLE "temporary_products" RENAME TO "products"`);
        await queryRunner.query(`CREATE INDEX "IDX_4c9fb58de893725258746385e1" ON "products" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_75895eeb1903f8a17816dafe0a" ON "products" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_048a28949bb332d397edb9b7ab" ON "products" ("stock") `);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "label" varchar(50) NOT NULL DEFAULT ('Home'), "fullName" varchar(100) NOT NULL, "phone" varchar(15) NOT NULL, "addressLine1" varchar(255) NOT NULL, "addressLine2" varchar(255), "city" varchar(100) NOT NULL, "state" varchar(100) NOT NULL, "pincode" varchar(10) NOT NULL, "isDefault" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_95c93a584de49f0b0e13f75363" ON "addresses" ("userId") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "amount" decimal(10,2) NOT NULL, "method" varchar(50) NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('pending'), "transactionId" varchar(100), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "orderId" integer NOT NULL, CONSTRAINT "REL_af929a5f2a400fdb6913b4967e" UNIQUE ("orderId"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rating" integer NOT NULL, "comment" text NOT NULL, "isVerifiedPurchase" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "productId" integer NOT NULL, CONSTRAINT "CHK_e87bbcfbe3ea0dda3d626010ee" CHECK ("rating" >= 1 AND "rating" <= 5))`);
        await queryRunner.query(`DROP INDEX "IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`CREATE TABLE "temporary_orders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "totalAmount" float NOT NULL, "paymentMethod" varchar(50) NOT NULL DEFAULT ('cash_on_delivery'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "status" varchar(50) NOT NULL DEFAULT ('pending'), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "shippingAddressId" integer, CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_orders"("id", "totalAmount", "paymentMethod", "createdAt", "userId", "status") SELECT "id", "totalAmount", "paymentMethod", "createdAt", "userId", "status" FROM "orders"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`ALTER TABLE "temporary_orders" RENAME TO "orders"`);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders" ("createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_4c9fb58de893725258746385e1"`);
        await queryRunner.query(`DROP INDEX "IDX_75895eeb1903f8a17816dafe0a"`);
        await queryRunner.query(`DROP INDEX "IDX_048a28949bb332d397edb9b7ab"`);
        await queryRunner.query(`CREATE TABLE "temporary_products" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(200) NOT NULL, "description" text NOT NULL, "price" decimal(10,2) NOT NULL, "stock" integer NOT NULL DEFAULT (0), "imagePath" text(255), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "subCategoryId" integer NOT NULL, CONSTRAINT "FK_ad42985fb27aa9016b16ee740ec" FOREIGN KEY ("subCategoryId") REFERENCES "sub_categories" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_products"("id", "name", "description", "price", "stock", "imagePath", "createdAt", "subCategoryId") SELECT "id", "name", "description", "price", "stock", "imagePath", "createdAt", "subCategoryId" FROM "products"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`ALTER TABLE "temporary_products" RENAME TO "products"`);
        await queryRunner.query(`CREATE INDEX "IDX_4c9fb58de893725258746385e1" ON "products" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_75895eeb1903f8a17816dafe0a" ON "products" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_048a28949bb332d397edb9b7ab" ON "products" ("stock") `);
        await queryRunner.query(`DROP INDEX "IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`CREATE TABLE "temporary_orders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "totalAmount" float NOT NULL, "paymentMethod" varchar(50) NOT NULL DEFAULT ('pay_on_delivery'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "status" varchar(50) NOT NULL DEFAULT ('pending'), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "shippingAddressId" integer, CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_orders"("id", "totalAmount", "paymentMethod", "createdAt", "userId", "status", "updatedAt", "shippingAddressId") SELECT "id", "totalAmount", "paymentMethod", "createdAt", "userId", "status", "updatedAt", "shippingAddressId" FROM "orders"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`ALTER TABLE "temporary_orders" RENAME TO "orders"`);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_151b79a83ba240b0cb31b2302d" ON "orders" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`DROP INDEX "IDX_95c93a584de49f0b0e13f75363"`);
        await queryRunner.query(`CREATE TABLE "temporary_addresses" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "label" varchar(50) NOT NULL DEFAULT ('Home'), "fullName" varchar(100) NOT NULL, "phone" varchar(15) NOT NULL, "addressLine1" varchar(255) NOT NULL, "addressLine2" varchar(255), "city" varchar(100) NOT NULL, "state" varchar(100) NOT NULL, "pincode" varchar(10) NOT NULL, "isDefault" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, CONSTRAINT "FK_95c93a584de49f0b0e13f753630" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_addresses"("id", "label", "fullName", "phone", "addressLine1", "addressLine2", "city", "state", "pincode", "isDefault", "createdAt", "updatedAt", "userId") SELECT "id", "label", "fullName", "phone", "addressLine1", "addressLine2", "city", "state", "pincode", "isDefault", "createdAt", "updatedAt", "userId" FROM "addresses"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`ALTER TABLE "temporary_addresses" RENAME TO "addresses"`);
        await queryRunner.query(`CREATE INDEX "IDX_95c93a584de49f0b0e13f75363" ON "addresses" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`DROP INDEX "IDX_151b79a83ba240b0cb31b2302d"`);
        await queryRunner.query(`CREATE TABLE "temporary_orders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "totalAmount" float NOT NULL, "paymentMethod" varchar(50) NOT NULL DEFAULT ('pay_on_delivery'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "status" varchar(50) NOT NULL DEFAULT ('pending'), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "shippingAddressId" integer, CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_cc4e4adab232e8c05026b2f345d" FOREIGN KEY ("shippingAddressId") REFERENCES "addresses" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_orders"("id", "totalAmount", "paymentMethod", "createdAt", "userId", "status", "updatedAt", "shippingAddressId") SELECT "id", "totalAmount", "paymentMethod", "createdAt", "userId", "status", "updatedAt", "shippingAddressId" FROM "orders"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`ALTER TABLE "temporary_orders" RENAME TO "orders"`);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_151b79a83ba240b0cb31b2302d" ON "orders" ("userId") `);
        await queryRunner.query(`CREATE TABLE "temporary_payments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "amount" decimal(10,2) NOT NULL, "method" varchar(50) NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('pending'), "transactionId" varchar(100), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "orderId" integer NOT NULL, CONSTRAINT "REL_af929a5f2a400fdb6913b4967e" UNIQUE ("orderId"), CONSTRAINT "FK_af929a5f2a400fdb6913b4967e1" FOREIGN KEY ("orderId") REFERENCES "orders" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_payments"("id", "amount", "method", "status", "transactionId", "createdAt", "orderId") SELECT "id", "amount", "method", "status", "transactionId", "createdAt", "orderId" FROM "payments"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`ALTER TABLE "temporary_payments" RENAME TO "payments"`);
        await queryRunner.query(`CREATE TABLE "temporary_reviews" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rating" integer NOT NULL, "comment" text NOT NULL, "isVerifiedPurchase" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "productId" integer NOT NULL, CONSTRAINT "CHK_e87bbcfbe3ea0dda3d626010ee" CHECK ("rating" >= 1 AND "rating" <= 5), CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a6b3c434392f5d10ec171043666" FOREIGN KEY ("productId") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_reviews"("id", "rating", "comment", "isVerifiedPurchase", "createdAt", "userId", "productId") SELECT "id", "rating", "comment", "isVerifiedPurchase", "createdAt", "userId", "productId" FROM "reviews"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`ALTER TABLE "temporary_reviews" RENAME TO "reviews"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reviews" RENAME TO "temporary_reviews"`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rating" integer NOT NULL, "comment" text NOT NULL, "isVerifiedPurchase" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "productId" integer NOT NULL, CONSTRAINT "CHK_e87bbcfbe3ea0dda3d626010ee" CHECK ("rating" >= 1 AND "rating" <= 5))`);
        await queryRunner.query(`INSERT INTO "reviews"("id", "rating", "comment", "isVerifiedPurchase", "createdAt", "userId", "productId") SELECT "id", "rating", "comment", "isVerifiedPurchase", "createdAt", "userId", "productId" FROM "temporary_reviews"`);
        await queryRunner.query(`DROP TABLE "temporary_reviews"`);
        await queryRunner.query(`ALTER TABLE "payments" RENAME TO "temporary_payments"`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "amount" decimal(10,2) NOT NULL, "method" varchar(50) NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('pending'), "transactionId" varchar(100), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "orderId" integer NOT NULL, CONSTRAINT "REL_af929a5f2a400fdb6913b4967e" UNIQUE ("orderId"))`);
        await queryRunner.query(`INSERT INTO "payments"("id", "amount", "method", "status", "transactionId", "createdAt", "orderId") SELECT "id", "amount", "method", "status", "transactionId", "createdAt", "orderId" FROM "temporary_payments"`);
        await queryRunner.query(`DROP TABLE "temporary_payments"`);
        await queryRunner.query(`DROP INDEX "IDX_151b79a83ba240b0cb31b2302d"`);
        await queryRunner.query(`DROP INDEX "IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`ALTER TABLE "orders" RENAME TO "temporary_orders"`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "totalAmount" float NOT NULL, "paymentMethod" varchar(50) NOT NULL DEFAULT ('pay_on_delivery'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "status" varchar(50) NOT NULL DEFAULT ('pending'), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "shippingAddressId" integer, CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "orders"("id", "totalAmount", "paymentMethod", "createdAt", "userId", "status", "updatedAt", "shippingAddressId") SELECT "id", "totalAmount", "paymentMethod", "createdAt", "userId", "status", "updatedAt", "shippingAddressId" FROM "temporary_orders"`);
        await queryRunner.query(`DROP TABLE "temporary_orders"`);
        await queryRunner.query(`CREATE INDEX "IDX_151b79a83ba240b0cb31b2302d" ON "orders" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders" ("createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_95c93a584de49f0b0e13f75363"`);
        await queryRunner.query(`ALTER TABLE "addresses" RENAME TO "temporary_addresses"`);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "label" varchar(50) NOT NULL DEFAULT ('Home'), "fullName" varchar(100) NOT NULL, "phone" varchar(15) NOT NULL, "addressLine1" varchar(255) NOT NULL, "addressLine2" varchar(255), "city" varchar(100) NOT NULL, "state" varchar(100) NOT NULL, "pincode" varchar(10) NOT NULL, "isDefault" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "addresses"("id", "label", "fullName", "phone", "addressLine1", "addressLine2", "city", "state", "pincode", "isDefault", "createdAt", "updatedAt", "userId") SELECT "id", "label", "fullName", "phone", "addressLine1", "addressLine2", "city", "state", "pincode", "isDefault", "createdAt", "updatedAt", "userId" FROM "temporary_addresses"`);
        await queryRunner.query(`DROP TABLE "temporary_addresses"`);
        await queryRunner.query(`CREATE INDEX "IDX_95c93a584de49f0b0e13f75363" ON "addresses" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "IDX_151b79a83ba240b0cb31b2302d"`);
        await queryRunner.query(`DROP INDEX "IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`ALTER TABLE "orders" RENAME TO "temporary_orders"`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "totalAmount" float NOT NULL, "paymentMethod" varchar(50) NOT NULL DEFAULT ('cash_on_delivery'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "status" varchar(50) NOT NULL DEFAULT ('pending'), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "shippingAddressId" integer, CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "orders"("id", "totalAmount", "paymentMethod", "createdAt", "userId", "status", "updatedAt", "shippingAddressId") SELECT "id", "totalAmount", "paymentMethod", "createdAt", "userId", "status", "updatedAt", "shippingAddressId" FROM "temporary_orders"`);
        await queryRunner.query(`DROP TABLE "temporary_orders"`);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders" ("createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_048a28949bb332d397edb9b7ab"`);
        await queryRunner.query(`DROP INDEX "IDX_75895eeb1903f8a17816dafe0a"`);
        await queryRunner.query(`DROP INDEX "IDX_4c9fb58de893725258746385e1"`);
        await queryRunner.query(`ALTER TABLE "products" RENAME TO "temporary_products"`);
        await queryRunner.query(`CREATE TABLE "products" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(200) NOT NULL, "description" text NOT NULL, "price" decimal(10,2) NOT NULL, "stock" integer NOT NULL DEFAULT (0), "imagePath" varchar(255), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "subCategoryId" integer NOT NULL, CONSTRAINT "FK_ad42985fb27aa9016b16ee740ec" FOREIGN KEY ("subCategoryId") REFERENCES "sub_categories" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "products"("id", "name", "description", "price", "stock", "imagePath", "createdAt", "subCategoryId") SELECT "id", "name", "description", "price", "stock", "imagePath", "createdAt", "subCategoryId" FROM "temporary_products"`);
        await queryRunner.query(`DROP TABLE "temporary_products"`);
        await queryRunner.query(`CREATE INDEX "IDX_048a28949bb332d397edb9b7ab" ON "products" ("stock") `);
        await queryRunner.query(`CREATE INDEX "IDX_75895eeb1903f8a17816dafe0a" ON "products" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c9fb58de893725258746385e1" ON "products" ("name") `);
        await queryRunner.query(`DROP INDEX "IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`ALTER TABLE "orders" RENAME TO "temporary_orders"`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "totalAmount" float NOT NULL, "paymentMethod" varchar(50) NOT NULL DEFAULT ('cash_on_delivery'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "status" varchar(50) NOT NULL DEFAULT ('pending'), CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "orders"("id", "totalAmount", "paymentMethod", "createdAt", "userId", "status") SELECT "id", "totalAmount", "paymentMethod", "createdAt", "userId", "status" FROM "temporary_orders"`);
        await queryRunner.query(`DROP TABLE "temporary_orders"`);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders" ("createdAt") `);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP INDEX "IDX_95c93a584de49f0b0e13f75363"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP INDEX "IDX_048a28949bb332d397edb9b7ab"`);
        await queryRunner.query(`DROP INDEX "IDX_75895eeb1903f8a17816dafe0a"`);
        await queryRunner.query(`DROP INDEX "IDX_4c9fb58de893725258746385e1"`);
        await queryRunner.query(`ALTER TABLE "products" RENAME TO "temporary_products"`);
        await queryRunner.query(`CREATE TABLE "products" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(200) NOT NULL, "description" text NOT NULL, "price" decimal(10,2) NOT NULL, "stock" integer NOT NULL DEFAULT (0), "imagePath" varchar(255), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "subCategoryId" integer NOT NULL, CONSTRAINT "FK_ad42985fb27aa9016b16ee740ec" FOREIGN KEY ("subCategoryId") REFERENCES "sub_categories" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "products"("id", "name", "description", "price", "stock", "imagePath", "createdAt", "subCategoryId") SELECT "id", "name", "description", "price", "stock", "imagePath", "createdAt", "subCategoryId" FROM "temporary_products"`);
        await queryRunner.query(`DROP TABLE "temporary_products"`);
        await queryRunner.query(`CREATE INDEX "IDX_048a28949bb332d397edb9b7ab" ON "products" ("stock") `);
        await queryRunner.query(`CREATE INDEX "IDX_75895eeb1903f8a17816dafe0a" ON "products" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c9fb58de893725258746385e1" ON "products" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
    }

}
